EXPORT_OPTIONS=master_logo.svg --export-area-page --export-area-snap --export-overwrite 

svg:
	inkscape ${EXPORT_OPTIONS} --export-plain-svg  --export-type=svg -o tart_logo.svg

png:
	inkscape ${EXPORT_OPTIONS} --export-dpi=300  --export-type=png -o tart_logo.png
	
